version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Oslo

  whisper:
    build:
      context: ./whisper
      dockerfile: dockerfile
    volumes:
      - ./audio:/app/audio
    command: sleep infinity

  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./scripts:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
